import { create } from "zustand";
import { useAppStore } from "./useAppStore";

export interface Playlist {
  id: string;
  name: string;
  description?: string;
  isAutoGenerated: boolean;
  trackIds: string[];
}

export interface MusicVideo {
  id: string;
  title: string;
  artistId: string;
  trackId?: string;
  url: string;
  thumbnailPath?: string;
  duration?: number;
}

interface PlaylistState {
  playlists: Playlist[];
  musicVideos: MusicVideo[];
  isLoading: boolean;
  error: string | null;

  // Playlists
  createPlaylist: (name: string, description?: string) => Promise<void>;
  deletePlaylist: (id: string) => Promise<void>;
  addTrackToPlaylist: (playlistId: string, trackId: string) => Promise<void>;
  removeTrackFromPlaylist: (
    playlistId: string,
    trackId: string,
  ) => Promise<void>;
  generateAutoPlaylist: (name: string, trackCount: number) => Promise<void>;
  loadPlaylists: () => Promise<void>;

  // Music Videos
  addMusicVideo: (
    title: string,
    artistId: string,
    url: string,
    trackId?: string,
  ) => Promise<void>;
  deleteMusicVideo: (id: string) => Promise<void>;
  loadMusicVideos: () => Promise<void>;
}

export const usePlaylistStore = create<PlaylistState>((set) => ({
  playlists: [],
  musicVideos: [],
  isLoading: false,
  error: null,

  createPlaylist: async (name, description) => {
    try {
      const id = `playlist_${Date.now()}`;
      set((state) => ({
        playlists: [
          ...state.playlists,
          { id, name, description, isAutoGenerated: false, trackIds: [] },
        ],
      }));
    } catch (err) {
      const errorMsg = err instanceof Error ? err.message : String(err);
      set({ error: errorMsg });
    }
  },

  deletePlaylist: async (id) => {
    try {
      set((state) => ({
        playlists: state.playlists.filter((p) => p.id !== id),
      }));
    } catch (err) {
      const errorMsg = err instanceof Error ? err.message : String(err);
      set({ error: errorMsg });
    }
  },

  addTrackToPlaylist: async (playlistId, trackId) => {
    try {
      set((state) => ({
        playlists: state.playlists.map((p) =>
          p.id === playlistId && !p.trackIds.includes(trackId)
            ? { ...p, trackIds: [...p.trackIds, trackId] }
            : p,
        ),
      }));
    } catch (err) {
      const errorMsg = err instanceof Error ? err.message : String(err);
      set({ error: errorMsg });
    }
  },

  removeTrackFromPlaylist: async (playlistId, trackId) => {
    try {
      set((state) => ({
        playlists: state.playlists.map((p) =>
          p.id === playlistId
            ? { ...p, trackIds: p.trackIds.filter((id) => id !== trackId) }
            : p,
        ),
      }));
    } catch (err) {
      const errorMsg = err instanceof Error ? err.message : String(err);
      set({ error: errorMsg });
    }
  },

  generateAutoPlaylist: async (name, trackCount) => {
    try {
      // Randomly pick track IDs from the currently loaded library (client-side fallback).
      // The Tauri backend does not expose a generate_random_playlist command, so we
      // build the playlist from the in-memory track list instead.
      const allTracks = useAppStore.getState().customTracks;
      const shuffled = [...allTracks].sort(() => Math.random() - 0.5);
      const result = shuffled.slice(0, trackCount).map((t) => t.id);
      const id = `playlist_${Date.now()}`;
      set((state) => ({
        playlists: [
          ...state.playlists,
          {
            id,
            name,
            description: "Für dich angefertigt",
            isAutoGenerated: true,
            trackIds: result,
          },
        ],
      }));
    } catch (err) {
      const errorMsg = err instanceof Error ? err.message : String(err);
      set({ error: errorMsg });
    }
  },

  loadPlaylists: async () => {
    set({ isLoading: true });
    try {
      // Playlists aus DB laden
      set({ isLoading: false });
    } catch (err) {
      const errorMsg = err instanceof Error ? err.message : String(err);
      set({ error: errorMsg, isLoading: false });
    }
  },

  addMusicVideo: async (title, artistId, url, trackId) => {
    try {
      const id = `video_${Date.now()}`;
      set((state) => ({
        musicVideos: [
          ...state.musicVideos,
          { id, title, artistId, url, trackId },
        ],
      }));
    } catch (err) {
      const errorMsg = err instanceof Error ? err.message : String(err);
      set({ error: errorMsg });
    }
  },

  deleteMusicVideo: async (id) => {
    try {
      set((state) => ({
        musicVideos: state.musicVideos.filter((v) => v.id !== id),
      }));
    } catch (err) {
      const errorMsg = err instanceof Error ? err.message : String(err);
      set({ error: errorMsg });
    }
  },

  loadMusicVideos: async () => {
    set({ isLoading: true });
    try {
      // Videos aus DB laden
      set({ isLoading: false });
    } catch (err) {
      const errorMsg = err instanceof Error ? err.message : String(err);
      set({ error: errorMsg, isLoading: false });
    }
  },
}));
