import { useEffect } from "react";
import { usePlaylistStore } from "../store/usePlaylistStore";
import { useAppStore } from "../store/useAppStore";
import { Play } from "lucide-react";

interface HomePageProps {
  onNavigate: (view: string, data?: any) => void;
}

export function HomePage({ onNavigate }: HomePageProps) {
  const { playlists, generateAutoPlaylist } = usePlaylistStore();
  const { customTracks, playTrack, topTracks, loadTopTracks } = useAppStore();

  useEffect(() => {
    loadTopTracks();
  }, []);

  useEffect(() => {
    // Generiere automatische Playlists beim ersten Laden
    if (playlists.filter((p) => p.isAutoGenerated).length === 0) {
      generateAutoPlaylist("Für dich angefertigt", 15);
      generateAutoPlaylist("Deine Top-Hits", 12);
      generateAutoPlaylist("Neu entdeckt", 10);
    }
  }, []);

  const autoPlaylists = playlists.filter((p) => p.isAutoGenerated);

  return (
    <div
      style={{ padding: "40px 48px", flex: 1, overflowY: "auto" }}
      className="custom-scrollbar"
    >
      <h1
        style={{
          fontSize: 44,
          fontWeight: 800,
          marginBottom: 8,
          letterSpacing: "-0.03em",
        }}
      >
        Willkommen
      </h1>
      <p
        style={{
          fontSize: 14,
          color: "var(--text-secondary)",
          marginBottom: 48,
        }}
      >
        {customTracks.length} Lieder in deiner Bibliothek
      </p>

      {/* Top Hits */}
      {topTracks.length > 0 && (
        <div style={{ marginBottom: 48 }}>
          <h2
            style={{
              fontSize: 20,
              fontWeight: 700,
              marginBottom: 16,
              letterSpacing: "-0.02em",
            }}
          >
            Top Hits
          </h2>
          {topTracks.slice(0, 10).map((track, index) => (
            <div
              key={track.id}
              onClick={() => playTrack(track)}
              style={{
                display: "flex",
                alignItems: "center",
                gap: 12,
                padding: "8px 10px",
                cursor: "pointer",
                borderRadius: 10,
                transition: "background 0.15s",
              }}
              onMouseEnter={(e) => {
                (e.currentTarget as HTMLElement).style.background =
                  "var(--surface-2)";
              }}
              onMouseLeave={(e) => {
                (e.currentTarget as HTMLElement).style.background =
                  "transparent";
              }}
            >
              {/* Rank */}
              <span
                style={{
                  width: 20,
                  textAlign: "center",
                  color: "var(--accent)",
                  fontWeight: 700,
                  fontVariantNumeric: "tabular-nums",
                  fontSize: 14,
                  flexShrink: 0,
                }}
              >
                {index + 1}
              </span>
              {/* Album art placeholder */}
              <div
                style={{
                  width: 40,
                  height: 40,
                  background: "var(--surface-3)",
                  borderRadius: 8,
                  border: "1px solid var(--border)",
                  flexShrink: 0,
                }}
              />
              {/* Title + artist */}
              <div style={{ flex: 1, minWidth: 0, overflow: "hidden" }}>
                <p
                  style={{
                    fontSize: 13,
                    fontWeight: 500,
                    marginBottom: 2,
                    overflow: "hidden",
                    textOverflow: "ellipsis",
                    whiteSpace: "nowrap",
                  }}
                >
                  {track.title}
                </p>
                <p
                  style={{
                    fontSize: 11,
                    color: "var(--text-muted)",
                    overflow: "hidden",
                    textOverflow: "ellipsis",
                    whiteSpace: "nowrap",
                  }}
                >
                  {track.artist}
                </p>
              </div>
              {/* Play count badge */}
              <span
                style={{
                  fontSize: 10,
                  background: "var(--accent-dim)",
                  color: "var(--accent)",
                  borderRadius: 99,
                  padding: "2px 8px",
                  whiteSpace: "nowrap",
                  flexShrink: 0,
                }}
              >
                {track.play_count} Plays
              </span>
            </div>
          ))}
        </div>
      )}

      {/* Featured Playlists */}
      {autoPlaylists.length > 0 && (
        <div style={{ marginBottom: 56 }}>
          <h2 style={{ fontSize: 24, fontWeight: 700, marginBottom: 20 }}>
            Für dich angefertigt
          </h2>
          <div
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))",
              gap: 20,
            }}
          >
            {autoPlaylists.slice(0, 3).map((playlist) => {
              const playlistTracks = customTracks.filter((t) =>
                playlist.trackIds.includes(t.id),
              );
              const coverGradients = [
                "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
                "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)",
                "linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)",
                "linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)",
              ];
              const gradient =
                coverGradients[
                  parseInt(playlist.id.split("_")[1] || "0", 10) %
                    coverGradients.length
                ];

              return (
                <div
                  key={playlist.id}
                  style={{
                    background: "var(--surface-1)",
                    border: "1px solid var(--border)",
                    borderRadius: 14,
                    overflow: "hidden",
                    cursor: "pointer",
                    transition: "transform 0.2s, box-shadow 0.2s",
                  }}
                  onMouseEnter={(e) => {
                    (e.currentTarget as HTMLElement).style.transform =
                      "translateY(-4px)";
                    (e.currentTarget as HTMLElement).style.boxShadow =
                      "0 12px 32px rgba(0,0,0,0.4)";
                  }}
                  onMouseLeave={(e) => {
                    (e.currentTarget as HTMLElement).style.transform =
                      "translateY(0)";
                    (e.currentTarget as HTMLElement).style.boxShadow = "none";
                  }}
                >
                  <div
                    style={{
                      background: gradient,
                      height: 140,
                      display: "flex",
                      alignItems: "flex-end",
                      justifyContent: "flex-end",
                      padding: 12,
                      position: "relative",
                    }}
                  >
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        if (playlistTracks.length > 0) {
                          playTrack(playlistTracks[0]);
                        }
                      }}
                      style={{
                        width: 48,
                        height: 48,
                        borderRadius: 24,
                        background: "var(--accent)",
                        border: "none",
                        cursor: "pointer",
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center",
                        color: "var(--surface-0)",
                        transition: "all 0.2s",
                      }}
                      onMouseEnter={(e) => {
                        (e.currentTarget as HTMLElement).style.transform =
                          "scale(1.1)";
                        (e.currentTarget as HTMLElement).style.boxShadow =
                          "0 4px 16px var(--accent-glow)";
                      }}
                      onMouseLeave={(e) => {
                        (e.currentTarget as HTMLElement).style.transform =
                          "scale(1)";
                        (e.currentTarget as HTMLElement).style.boxShadow =
                          "none";
                      }}
                    >
                      <Play
                        size={20}
                        color="var(--surface-0)"
                        fill="var(--surface-0)"
                      />
                    </button>
                  </div>
                  <div
                    style={{ padding: 16, cursor: "pointer" }}
                    onClick={() =>
                      onNavigate("playlists", { playlistId: playlist.id })
                    }
                  >
                    <h3
                      style={{ fontWeight: 600, marginBottom: 4, fontSize: 15 }}
                    >
                      {playlist.name}
                    </h3>
                    <p
                      style={{
                        fontSize: 12,
                        color: "var(--text-secondary)",
                        marginBottom: 8,
                      }}
                    >
                      {playlistTracks.length} Lieder
                    </p>
                    {playlist.description && (
                      <p
                        style={{
                          fontSize: 11,
                          color: "var(--text-secondary)",
                          fontStyle: "italic",
                        }}
                      >
                        {playlist.description}
                      </p>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Recent Artists */}
      {customTracks.length > 0 && (
        <div>
          <h2
            style={{
              fontSize: 20,
              fontWeight: 700,
              marginBottom: 20,
              letterSpacing: "-0.03em",
            }}
          >
            Künstler
          </h2>
          <div
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(auto-fill, minmax(140px, 1fr))",
              gap: 12,
            }}
          >
            {[...new Set(customTracks.map((t) => t.artist))]
              .slice(0, 8)
              .map((artist) => (
                <button
                  key={artist}
                  onClick={() => onNavigate("artist", { artist })}
                  style={{
                    padding: "12px 16px",
                    background: "var(--surface-2)",
                    border: "1px solid var(--border)",
                    borderRadius: 99,
                    cursor: "pointer",
                    fontSize: 13,
                    fontWeight: 500,
                    color: "var(--text-secondary)",
                    transition: "all 0.2s",
                  }}
                  onMouseEnter={(e) => {
                    const el = e.currentTarget as HTMLElement;
                    el.style.background = "var(--surface-3)";
                    el.style.color = "var(--text-primary)";
                    el.style.borderColor = "var(--border-hover)";
                  }}
                  onMouseLeave={(e) => {
                    const el = e.currentTarget as HTMLElement;
                    el.style.background = "var(--surface-2)";
                    el.style.color = "var(--text-secondary)";
                    el.style.borderColor = "var(--border)";
                  }}
                >
                  {artist}
                </button>
              ))}
          </div>
        </div>
      )}
    </div>
  );
}
