name: Build ArtMusic

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      # Node setup
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      # Install dependencies
      - name: Install npm dependencies
        run: npm install
      
      # Build frontend
      - name: Build frontend
        run: npm run build
      
      # Upload dist
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
